language: elixir
elixir:
  - 1.6.6
otp_release:
  - 20.3.8.2
#matrix:
#  exclude:
#    - elixir: 1.6.6
#      otp_release: 17.5
sudo: false # to use faster container based build environment
script:
- mix test
